"""``rookery init`` — scaffold a project directory.

Creates rookery.yaml, rookery.db (with migrations), parcels/,
worktrees/ + worktrees/.gitignore, and appends entries to .gitignore.
"""

from __future__ import annotations

from pathlib import Path

from rookery.orchestrator.schema import apply_migrations

# ---------------------------------------------------------------------------
# YAML template — inline so comments are preserved (no model dump)
# ---------------------------------------------------------------------------

_CONFIG_TEMPLATE = """\
# rookery.yaml — generated by `rookery init`
# Edit as needed. All values shown are the defaults.

# ---------------------------------------------------------------------------
# Storage
# ---------------------------------------------------------------------------
db_path: ./rookery.db          # SQLite queue database
worktrees_root: ./worktrees         # git worktrees are created here

# ---------------------------------------------------------------------------
# Daemon
# ---------------------------------------------------------------------------
max_concurrent: 4                   # worker slots (parallel parcels)
tick_interval_s: 5                  # scheduler poll interval in seconds
lease_ttl_s: 1800                   # claim lease lifetime (30 min)
shutdown_grace_s: 30                # SIGTERM → SIGKILL grace period

# ---------------------------------------------------------------------------
# Worker spawn
# ---------------------------------------------------------------------------
backend: local                      # local | managed_agents (stub)
claude_profile: null                # ~/.claude-profiles/<name>, null = default

# ---------------------------------------------------------------------------
# Verdict
# ---------------------------------------------------------------------------
# How workers signal completion. Built-ins: marker-file | exit-code | json-result
# verdict_adapter: marker-file

# ---------------------------------------------------------------------------
# Auto-land (off by default — operator opts in)
# ---------------------------------------------------------------------------
auto_land: false
auto_land_timeout_s: 1800
auto_land_test_cmd: "uv run pytest tests/"

# ---------------------------------------------------------------------------
# Auto-retire (off by default — operator opts in)
# ---------------------------------------------------------------------------
auto_retire: false
auto_retire_idle_minutes: 60
auto_retire_batch_size: 1

# ---------------------------------------------------------------------------
# Audit loop
# ---------------------------------------------------------------------------
audit_loop:
  max_iter: 3
  audit_backoff_s: 5
"""

# Lines we guarantee are in the root .gitignore
_GITIGNORE_ENTRIES: list[str] = [
    "rookery.db",
    "rookery.db-wal",
    "rookery.db-shm",
    "*.log",
    "worktrees/",
]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


class InitError(RuntimeError):
    """Raised when init preconditions are not met."""


def cmd_init(target_dir: Path = Path("."), force: bool = False) -> None:
    """Scaffold a rookery project in *target_dir*.

    Creates:
    - ``rookery.yaml``  — config template with inline comments
    - ``rookery.db``    — SQLite database with all migrations applied
    - ``parcels/``           — directory for parcel markdown files
    - ``worktrees/``         — directory for git worktrees
    - ``worktrees/.gitignore`` — ``*`` so worktree contents are ignored
    - ``.gitignore``         — appended with DB / log / worktrees entries

    Args:
        target_dir: Directory to initialise. Created if absent.
        force: If True, overwrite ``rookery.yaml`` even if it exists and
               re-run migrations against an existing DB (migrations are
               idempotent).

    Raises:
        InitError: When ``rookery.yaml`` already exists and
                   ``force`` is False.
    """
    target_dir = target_dir.resolve()
    target_dir.mkdir(parents=True, exist_ok=True)

    config_path = target_dir / "rookery.yaml"
    if config_path.exists() and not force:
        raise InitError(
            f"{config_path} already exists. "
            "Pass force=True (or --force on the CLI) to overwrite."
        )

    # 1. Write rookery.yaml
    config_path.write_text(_CONFIG_TEMPLATE, encoding="utf-8")

    # 2. Create rookery.db and run all migrations
    db_path = target_dir / "rookery.db"
    apply_migrations(db_path)

    # 3. parcels/ + .gitkeep
    parcels_dir = target_dir / "parcels"
    parcels_dir.mkdir(exist_ok=True)
    gitkeep = parcels_dir / ".gitkeep"
    if not gitkeep.exists():
        gitkeep.touch()

    # 4. worktrees/ + .gitignore (ignore all contents by default)
    worktrees_dir = target_dir / "worktrees"
    worktrees_dir.mkdir(exist_ok=True)
    wt_gitignore = worktrees_dir / ".gitignore"
    if not wt_gitignore.exists():
        wt_gitignore.write_text("*\n", encoding="utf-8")

    # 5. Root .gitignore — idempotent append
    _update_gitignore(target_dir / ".gitignore", _GITIGNORE_ENTRIES)


def _update_gitignore(gitignore_path: Path, entries: list[str]) -> None:
    """Append *entries* to *gitignore_path*, skipping lines already present.

    Creates the file if it does not exist. Existing content is preserved
    exactly; we only append lines that are not already in the file.
    """
    existing_lines: list[str] = []
    if gitignore_path.exists():
        existing_lines = gitignore_path.read_text(encoding="utf-8").splitlines()

    existing_set = {line.strip() for line in existing_lines}
    missing = [e for e in entries if e not in existing_set]
    if not missing:
        return

    # Ensure the file ends with a newline before we append
    prefix = ""
    if existing_lines and existing_lines[-1].strip() != "":
        prefix = "\n"

    with gitignore_path.open("a", encoding="utf-8") as fh:
        fh.write(prefix)
        for entry in missing:
            fh.write(entry + "\n")


__all__ = ["InitError", "cmd_init"]
